### ISSUE TITLE
Chat error {luckperms support}

### ISSUE THREAD

**Issue by BigDrewskii** [AddstarMC/BungeeChat#1]
I receive this error when attempting to type into chat. http://pastebin.com/Ht9RGJmV

Running Servers on SpongeForge
BungeeCord proxy V 1205
Bungeechat V 1.3.0.b1_104
LuckpermsBungee V 2.15.16
LuckPermsSponge V 2.15.16

Thanks

**Comment by Narimm** [comment]
You are not using our version of Bungeechat which is @ 1.1.0 currently...I would suggest your using the official version
https://www.spigotmc.org/resources/bungee-chat.12592/
